---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-stack
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 61.9.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    alertmanager:
      ingress:
        enabled: true
        ingressClassName: internal
        hosts:
          - "alertmanager.${SECRET_DOMAIN}"
        paths:
          - /
    grafana:
      ingress:
        enabled: true
        ingressClassName: internal
        hosts:
          - "grafana.${SECRET_DOMAIN}"
        paths:
          - /
    prometheus:
      ingress:
        enabled: true
        ingressClassName: internal
        hosts:
          - "prometheus.${SECRET_DOMAIN}"
        paths:
          - /
