---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jupyterhub
spec:
  interval: 30m
  chart:
    spec:
      chart: jupyterhub
      version: 3.3.8
      sourceRef:
        kind: HelmRepository
        name: jupyterhub
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
