---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aerospike-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: aerospike-kubernetes-operator
      version: 3.3.1
      sourceRef:
        kind: HelmRepository
        name: aerospike
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
