---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1gdz96zavnm9msl7j9gp8esfuhkhjjh3zdjy056ahnu2l5dk8sevscjpv3f"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1gdz96zavnm9msl7j9gp8esfuhkhjjh3zdjy056ahnu2l5dk8sevscjpv3f"
