apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: registry
  name: registry
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      run: registry
  template:
    metadata:
      labels:
        run: registry
    spec:
      containers:
      - name: registry
        image: registry:2
        ports:
          - name: registry
            containerPort: 5000
            protocol: TCP
        volumeMounts:
        - name: registry-data
          mountPath: /var/lib/registry
          subPath: registry
        - mountPath: "/etc/docker/registry"
          name: "config"
        livenessProbe:
          httpGet:
            path: /v2/
            port: registry
        readinessProbe:
          httpGet:
            path: /v2/
            port: registry          
      volumes:
      - name: registry-data
        persistentVolumeClaim:
          claimName: registry-data
      - name: config
        configMap:
          defaultMode: 420
          name: docker-registry