apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: konsole
spec:
  ingressClassName: internal
  rules:
    - host: konsole.vegmond.net
      http:
        paths:
          - backend:
              service:
                name: console
                port:
                  number: 80
            path: /
            pathType: Prefix
