---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./coredns.yaml
  - ./jetstack.yaml
  - ./metrics-server.yaml
  - ./openebs.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./spegel.yaml
  - ./stakater.yaml
  - ./external-dns.yaml
  - ./ingress-nginx.yaml
  - ./k8s-gateway.yaml
  - ./bitami.yaml
  - ./elastic.yaml
  - ./harbor.yaml
  - ./jupyterhub.yaml
  - ./rook.yaml
  - ./strimzi.yaml
  - ./zalando.yaml
  - ./conduktor.yaml
  - ./github-runner.yaml
  - ./gitea.yaml
  - ./enapter.yaml
