apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: my-bridge
spec:
  replicas: 3
  bootstrapServers: my-cluster-kafka-bootstrap:9092
  http:
    port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-bridge-ingress
spec:
  ingressClassName: internal
  rules:
    - host: mario-kafka.vegmond.net
      http:
        paths:
          - backend:
              service:
                name: my-bridge-bridge-service
                port:
                  name: rest-api
            path: /
            pathType: Prefix
