apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:ysFwM8wz5LF1z7lRQIjUuWXHOoBe2PjXpaS6L8kMMRtwPXb9,iv:2atKWthJYgnYwI/omJqfHgxuYvLRRrximCnOoxYB16w=,tag:rsal59IJgZP+4a0kZ/ymlQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:i/wzbLg6FaENX7YJxpfqJq4Z30hQM1LKzBwmpiJ84+FECH1dEy2H9hAir2DOa6KIjix3IsfYM5tviaZ5W1nkugy9vYPg8Eh4jW5PAF5Mu1+zJlm/IBVtaQLeAXRS0iysQfQ/SsNChtq3P6JdjFASlLNcfg1X8t9VYY7fjJ787IQMEasywGThS2Q1Vw6/KH/j7ByzqgtqgtxQro4tTL2Om60678gZ5UgKptGm/hDLLA==,iv:SVfYaaDCvdg95TBly9xQV2IGCCzsfnfCKXiCEu+uRt8=,tag:NdEwAR/4OgNpOw5cSoruYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gdz96zavnm9msl7j9gp8esfuhkhjjh3zdjy056ahnu2l5dk8sevscjpv3f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPNkpkUzRlVUx6RVdJaGg5
            M2psNlljKzdOeEk5TnUwUDNRZDI0amhtZ0FrCmdEUHhSY0tsRElScGdnNm5KTVhv
            eDJyN0IxTVJOejFITVBkZ091T09LeEkKLS0tIEJqUHQ3UHdOYnIzVkVnaHNJcjNB
            QkZBSFBtWkhDU0VBTG54NGFCTzRENDgKKxBpIonq4m12StaPraa7joZRzAXkW/dx
            K5cWAWEFS6BZlLdAyKsJpe77OPortecLujtYr9X21dzmTnbXfadkgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-20T15:21:40Z"
    mac: ENC[AES256_GCM,data:5TVw55i3Wj3m7uhSokVFSagwcg1XMCGW1EUGh5lXrRYgBG8KnFQpdJbBCciP9XPQyGbqWNQSLp50IyMu/LjnZph08axaUtATJMB2TUBZnPAb026yOaK36wbwtsdcsVIJRSoSKj3wEibEn85GxRBGS0JGaWx7SkJzD1A+hq9ATwk=,iv:rbXnrvaF/jT3drBsOJIvprk6WtMNdWEptuS72VdX9q0=,tag:XIo+M0WxysDPeikbXd+zuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
