---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-cluster
spec:
  interval: 30m
  chart:
    spec:
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: bitami
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    global:
      defaultStorageClass: csi-rbd-sc
    usePassword: true
    password: '0123456789'
    master:
      service:
        type: LoadBalancer
        loadBalancerSourceRanges:
          - 192.168.23.0/24
        annotations:
          "coredns.io/hostname": "redis.vegmond.net"
          external-dns.alpha.kubernetes.io/hostname: redis.vegmond.net
    metrics:
      enabled: true
