---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-cluster
spec:
  interval: 30m
  chart:
    spec:
      chart: redis-cluster
      version: 11.0.3
      sourceRef:
        kind: HelmRepository
        name: bitami
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    global:
      defaultStorageClass: "csi-rbd-sc"
      redis:
        password: ""

    ## @param usePassword Use password authentication
    ##
    usePassword: false
    ## @param password Redis&reg; password (ignored if existingSecret set)
    ## Defaults to a random 10-character alphanumeric string if not set and usePassword is true
    ## ref: https://github.com/bitnami/containers/tree/main/bitnami/redis#setting-the-server-password-on-first-run
    ##
    password: ""
    ## @param existingSecret Name of existing secret object (for password authentication)
    ##
    existingSecret: ""

    ## Enable persistence using Persistent Volume Claims
    ## ref: https://kubernetes.io/docs/concepts/storage/persistent-volumes/
    ##
    persistence:
      enabled: true
      size: 8Gi

    ## Redis&reg; Cluster settings
    ##
    cluster:
      ## @param cluster.init Enable the initialization of the Redis&reg; Cluster
      ##
      init: true
      ## Number of Redis&reg; nodes to be deployed
      ##
      ## Note:
      ## This is total number of nodes including the replicas. Meaning there will be 3 master and 3 replica
      ## nodes (as replica count is set to 1 by default, there will be 1 replica per master node).
      ## Hence, nodes = numberOfMasterNodes + numberOfMasterNodes * replicas
      ##
      ## @param cluster.nodes The number of master nodes should always be >= 3, otherwise cluster creation will fail
      ##
      nodes: 6
      ## @param cluster.replicas Number of replicas for every master in the cluster
      ## Parameter to be passed as --cluster-replicas to the redis-cli --cluster create
      ## 1 means that we want a replica for every master created
      ##
      replicas: 1
      ## Configuration to access the Redis&reg; Cluster from outside the Kubernetes cluster
    ##

    ## Prometheus Exporter / Metrics
    ##
    metrics:
      ## @param metrics.enabled Start a side-car prometheus exporter
      ##
      enabled: true
  