apiVersion: asdb.aerospike.com/v1
kind: AerospikeCluster
metadata:
  name: aerocluster
  namespace: aerospike
spec:
  size: 3
  image: aerospike/aerospike-server:7.1.0.5

  podSpec:
    multiPodPerHost: false

  storage:
    filesystemVolumePolicy:
      cascadeDelete: true
      initMethod: deleteFiles
    volumes:
      - name: workdir
        source:
          persistentVolume:
            storageClass: csi-rbd-sc
            volumeMode: Filesystem
            size: 3Gi
        aerospike:
          path: /opt/aerospike
      - name: ns
        aerospike:
          path: /test/dev/xvdf
        source:
          persistentVolume:
            storageClass: csi-rbd-sc
            volumeMode: Block
            size: 5Gi
      - name: aerospike-config-secret
        source:
          emptyDir: {}
          # secret:
          #   secretName: aerospike-secret
        aerospike:
          path: /etc/aerospike/secret

  # aerospikeAccessControl:
  #   users:
  #     - name: admin
  #       secretName: auth-secret
  #       roles:
  #         - sys-admin
  #         - user-admin

  aerospikeConfig:
    service:
      feature-key-file: /etc/aerospike/secret/features.conf
    #    security: {}
    network:
      service:
        port: 3000
      fabric:
        port: 3001
      heartbeat:
        port: 3002
    namespaces:
      - name: test
        replication-factor: 2
        storage-engine:
          type: device
          devices:
            - /test/dev/xvdf
