apiVersion: v1
kind: ConfigMap
metadata:
  name: aerospike-conf
data:
  aerospike.conf: |
    # Aerospike database configuration file for deployments using mesh heartbeats.

    service {
      user root
      group root
      pidfile /var/run/aerospike/asd.pid
      proto-fd-max 15000
      cluster-name mario
    }

    logging {
      # Log file must be an absolute path.
      file /var/log/aerospike/aerospike.log {
        context any info
      }
      # Send log messages to stdout
      console {
        context any info 
      }      
    }

    network {
      service {
        address eth0
        port 3000
      }

      heartbeat {
        address eth0
        mode mesh
        port 3002 # Heartbeat port for this node.

        interval 250
        timeout 10
      }

      fabric {
        address eth0
        port 3001
      }

    #	info {
    #		port 3003
    #	}
    }

    namespace mario {
      replication-factor 2

      storage-engine memory {
    		file /opt/aerospike/data/mario.dat
    		filesize 10G

      }
    }

    namespace config {
      replication-factor 2

      storage-engine memory {
        # To use file storage backing, comment out the line above and use the
        # following lines instead.
    		file /opt/aerospike/data/config.dat
    		filesize 4G
      }
    }
