apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:jrKIWy0p/LdOT9vj9n0bkj9AvHjFUPQ3TzSEEQXUPxN8yFGJDQfFXQ==,iv:sX4KKhTAd+KnNFucwkrbCroCZNrMJ+FapRy27cXl70c=,tag:b8iPN0x6y004YtU58oL2aw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gdz96zavnm9msl7j9gp8esfuhkhjjh3zdjy056ahnu2l5dk8sevscjpv3f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhS1BocVVXQXhMS2hpZTNR
            L21EUXN1NzRlK1J1ZEZ6RzdlbXZ3MkpWWnpZCnRjZUYydHJUSnNsSk84bjhFYUFz
            eHAwMWFJdnMwQ2VHYzYzTnQyaGxReGMKLS0tIDdENTBZcnlGWEs1ZFZaQlBMakJi
            M3VJcmRaeW8yTTUzZ0phc25HSDVubmsKSs5A8HNc9jSavzTDYNzH8UEYzm/lnQO5
            +vdNUbsj+gzd1sm8ax9A3Qc/nMgjPkhCGjcCeI2yN+0nNsd7K2y33w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-20T14:25:15Z"
    mac: ENC[AES256_GCM,data:LkY8UqyiisDy9zp7qKLOtlzFCZuurf8CYMguX0GR9D90UNSa6M+ss8gAuupry1ajWuVR2h2RWLj+4SWJ0BzHKOtN8qQc6VUGHqHOQsB0ahulwbkf2s+z4jlrO4pdAhUmMfLC02uzdUasPtG2foShXDIsM5N/CkKqHiJUm6UXJ5k=,iv:gIw0zbqSEY1d82JAT6ClnwT3m1IQo4vvLDWPdyyrpIs=,tag:+OXjV3oJrWqmA3x7gQbENw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
