apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:7HML9uX/RKDP60+N8EAmS5A+9v25TSujM+7a84gmjyWlsWR4gH0Jxw==,iv:YIhH0SgyLZqhUY9gs01Zt54V+L1gC7sIR21DuBvmUOU=,tag:oHcXahCDEhmpAwYeQSJsag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mpprfpndatzrv5e8hzt6wfwtc24tlawwagkx7x8hkwfxgluspsysafpuvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQM3g4RFU3UGNkZFdlQktO
            dFZpU0tzRHBIL21kazFxYnNya1VSeWxjOFM0Clcxa016ZU1MVDhETnBiL1pNa2Fl
            U3JmMXN1MWlFelFtZ2pMblk4cG1aczQKLS0tIEh1cDZCZzJ4WktpdVpnalh2eita
            NkNkTDhqaHByTUFIeXRYNUg4WU5jeTQKZ/6NUO2ZLnqbyfnHRK6EFoCOWicXR2e8
            fAueGYzYq9BrdEJRYfvN8UgrP2sP26F5GVvDNwQl9uMP061H4V/T/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-20T15:22:45Z"
    mac: ENC[AES256_GCM,data:gq0L1ne7PZX8fMT4vdm9CJxk4EVleQXdh2eqV2/4fOY6fAopZPHnElJVjsXBv/nqrvtzYZj5i7aGxni65oh5a9Y1NlfdKFneOUG14uMv5QMs5LbsmxhJ0gGnIU+3T74j0VzBD6JRsL4JhC3uTyR6Q1r3ReP+IB/B2pMz3A6bhCo=,iv:LjTQtGIn+snQWoo7FWdty7+livlJzkBxLfLDamHJ7Uo=,tag:NPsycb+ZG6mu5VxEWQo63Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
