apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:GydbcpR95tNdZ+wDSPjpIuUVs8KDcN/UahxFUYgTVef5iIrdcxcKAQ==,iv:GfvjWOPvl9H4YDzI5V58yhuaifvwprj+3/i9LRkgNoE=,tag:/QjhNQhogw2ucsfvMWw8Gg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gdz96zavnm9msl7j9gp8esfuhkhjjh3zdjy056ahnu2l5dk8sevscjpv3f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVS2JDU1JyTXh2UEN4endv
            U1MvZ0wvbjFuMmFTNEUyS2tBUGJDQlFGbFJNClVuc1VWVjJDaHlUYlJ0N081WnBL
            d3YyOFFrWnZseDJJM1VSZWRhcU5mTUkKLS0tIHVkaHRIZ1JSNm8vTGErNVVuSGpm
            RWdnYm9DOEpWY1lUcjFwK204a0pyTGsKPpiX+d+uXEfkU0ihzIAcDU5xMkNE+hd+
            yCc2cxpdKMcD7C6WyTTfsJ7k4Lrg2oViGC5Fv2WS2EeTKuQumECF0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-20T15:21:40Z"
    mac: ENC[AES256_GCM,data:vW/IGkBUr+Fzen+CNIvv0xASs+ffKW16MX874jvP9pbSJ2WiPAbtwGQPtjr1NUF45cpFi+LfB5z/CsIeODx/8Pu+fn1Jlf3PZvgNkyspgUxNTtrChzE00F7cz9XuW+luHBFTgD0cTvYfXRJY0K3asV3yAWova7qZHdt9tEffaG8=,iv:hEWfShR8CILQKhjUbjH5kwsL9hC9+q05MdMzOV/B/68=,tag:ylPoR1Z2Vd+LiRwXLwqK4g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
