---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  # - ./harbor/ks.yaml
  # - ./strimzi/ks.yaml
  # - ./conduktor/ks.yaml
  # - ./redis/ks.yaml
  # - ./gitea/ks.yaml
  # - ./proxpi/ks.yaml

