kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "conduktor-db"
  labels:
    team: acid

spec:
  teamId: "acid"
  postgresql:
    version: "16"
  numberOfInstances: 1
  volume:
    size: "10Gi"

  users:
    conduktor:
      - superuser
      - createdb

  databases:
    console: conduktor # dbname: owner

  allowedSourceRanges:
    # IP ranges to access your cluster go here

  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
