---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: github-runner
spec:
  interval: 30m
  chart:
    spec:
      chart: gha-runner-scale-set
      sourceRef:
        kind: HelmRepository
        name: github-runner
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  valuesFrom:
    - kind: Secret
      name: github-deploy-key
      valuesKey: identity
      targetPath: githubConfigSecret.github_token
      optional: false

  values:
    githubConfigUrl: "https://github.com/DotZero24"
