apiVersion: v1
stringData:
    htpasswd: ENC[AES256_GCM,data:2u0/LMP/P5rnAquNqhfvGnwoQ/BxIy0xSFmF0NcQ/8i8XDGAiHo4pk8Vxe7gJCm86471uwWhQ+kyTUTVDkTH0XolDzkmz3l9qDS3b6O2o39liy/PaeZBf+4kFedyLJGogIq7aZ5M,iv:MX2Hbyb6YXdGotBPd+4InaTArVRCjfOLuXBPkiv5UlE=,tag:QoufTw9XGXPUTs+y6tmpGw==,type:str]
kind: Secret
metadata:
    name: htpasswd
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mpprfpndatzrv5e8hzt6wfwtc24tlawwagkx7x8hkwfxgluspsysafpuvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMUtwRXBRTkswTHBOWXAx
            TUhQMkJjbzEvWVVOcHlYWktWdjNXTWdvMkdRCktzMXl5VTZRdUJZWGRlSG5Ua29p
            cUI4OFNlN2Z1ejNmcVBpcEtQY3BkNkEKLS0tIEdjeWRib1FGREkyb2g2MjdZZkpq
            eHgwRTlYVUpvVVZXc3FialNCK3dSU3MKN93nozinQmN/066MZKXaAoUvykxuFXMC
            JPOxlJQ7StyBGH15MVzM8iy7XoXJeA1/8eeddRl0kojdEAi2sXrS3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-02T08:37:11Z"
    mac: ENC[AES256_GCM,data:lz/yDN9LGxtKleiui8PyDlYm3GpvTP64A0olf4JBotyLt0SewmyFZ6Z/fmxubVt3VssNeVJ4Ij7fxpjq7b0UccjvnP5CEaAYm0BNHYn6oJf8DjirjLT9U8hp76YVkR1dGsnLPfpU3EkbdAwbRaxXJ3NCzDtuZtVSJ/d6cMGcyLQ=,iv:30QVin0kMcizfejNErIxKcLtcR8MlDmiUQy0x/M/BsU=,tag:oKoTaIVDm9o6V66h8ygakg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
