---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./controller.yaml
  - ./ksql.yaml
  - ./schema-registry.yaml
  - ./rest-proxy.yaml
  #- ./connect.yaml
  - ./control-center.yaml
