apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-rest-proxy
  name: kafka-rest-proxy
spec:
  ports:
    - name: tcp-rest-proxy
      port: 8082
      protocol: TCP
      targetPort: tcp-rest-proxy
  selector:
    app: kafka-rest-proxy
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: kafka-rest-proxy
  name: kafka-rest-proxy
spec:
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kafka-rest-proxy
  serviceName: kafka-rest-proxy
  template:
    metadata:
      labels:
        app: kafka-rest-proxy
    spec:
      serviceAccountName: kafka
      containers:
        - env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: KAFKA_REST_BOOTSTRAP_SERVERS
              value: kafka-0.kafka-headless.kafka.svc.cluster.local:9092,kafka-1.kafka-headless.kafka.svc.cluster.local:9092,kafka-2.kafka-headless.kafka.svc.cluster.local:9092
            - name: KAFKA_REST_LISTENERS
              value: http://0.0.0.0:8082
            - name: KAFKA_REST_SCHEMA_REGISTRY_URL
              value: http://kafka-schema-registry:8082

          name: rest-proxy
          image: confluentinc/cp-kafka-rest:7.5.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
              name: tcp-rest-proxy
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 1400Mi
            requests:
              cpu: 250m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            # readOnlyRootFilesystem: true
            runAsGroup: 1000
            runAsUser: 1000
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/kafka
              name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
      volumes:
        - emptyDir: {}
          name: config
