apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-schema-registry
  name: kafka-schema-registry
spec:
  ports:
    - name: tcp-schema-reg
      port: 8081
      protocol: TCP
      targetPort: tcp-schema-reg
  selector:
    app: kafka-schema-registry
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: kafka-schema-registry
  name: kafka-schema-registry
spec:
  podManagementPolicy: Parallel
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kafka-schema-registry
  serviceName: kafka-schema-registry
  template:
    metadata:
      labels:
        app: kafka-schema-registry
    spec:
      serviceAccountName: kafka
      containers:
        - env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: kafka-0.kafka-headless.kafka.svc.cluster.local:9092,kafka-1.kafka-headless.kafka.svc.cluster.local:9092,kafka-2.kafka-headless.kafka.svc.cluster.local:9092
            - name: SCHEMA_REGISTRY_LISTENERS
              value: http://0.0.0.0:8081
          name: schema-registry
          image: confluentinc/cp-schema-registry:7.5.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: tcp-schema-reg
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 1400Mi
            requests:
              cpu: 250m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            # readOnlyRootFilesystem: true
            runAsGroup: 1000
            runAsUser: 1000
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/kafka
              name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
      volumes:
        - emptyDir: {}
          name: config
