apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:xDtsOIC4Ej2/d5s=,iv:7dTjjngOyCOfbGuuE3L20QVreekns5vHR6yeny6muFI=,tag:KQnUv4B7uGfP7MgLvaq2XA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:NOhtT7ngNdZQIpGGcd8OLYfoBw==,iv:HmdIHs8hCW0OuE93PSEEfgVgvhKOJwIkFdQLSA8vkao=,tag:PCnwWAI/K1jpyk0iTmHrGw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:0R8UNoHWzbyFtNvM+h6ikniXGUwhCLjkJqjU9qTZ79lqLcTV,iv:tM5Q5yAhbzveT4ahORYdHsYuWrQEdoGgtGMkNd8njEc=,tag:Az7k8o+rACzOf4rQfR2a3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mpprfpndatzrv5e8hzt6wfwtc24tlawwagkx7x8hkwfxgluspsysafpuvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5L3c1NUYxSHVtMGZ4SUF1
            OGk3SnZlOGtnNVczYVRiVUJneUc4Q0ZhdVNVClF1T1d6eVpJZkpha0orTjNSR1Yv
            UWh2cUloY2M2eWl6QVVvYWZPYkZKOEEKLS0tIFZBV1pnWmQwbXB3eVdNeVVHMHBG
            cTVUVUFHa0lsL2FIU3ZPZ09IdVpxRXMKH7UGYt2SflvVZKc7DPYLleioOPHKCgNA
            LKkxPxcZGyAPwdsgJoozEb/hLcSjq7ofXAyUQc/riPI7ijFqgC7RFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-24T08:39:27Z"
    mac: ENC[AES256_GCM,data:l4DL5StATVPKfcy1V+6et8qFMBLozFcCOfEIjYLt5ijr+8/63cI5Vn2LMZEPh1mO6DnD8qdYLwf05T7+kDqbb7ZleOEDjBd8EqrztAyZYDH5ha/ko3R/73eRXwq9uKElWYctT6pFPL7bDa/N8Lf1pzOqKbYrP+QfewrhGKWMwZA=,iv:BY+XiKkwOAQUZLOCfFsz6HWUoKPPOjnK0s8EMe6Csrw=,tag:tkUem27X3txufAYe5swOfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
