---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aerospike-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: aerospike-kubernetes-operator
      version: 3.3.1
      sourceRef:
        kind: HelmRepository
        name: aerospike
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    aerospikeConfig:
      service:
        feature-key-file: /etc/aerospike/secrets/features.conf

      network:
        service:
          port: 3000
        fabric:
          port: 3001
        heartbeat:
          port: 3002

      namespaces:
        - name: test
          replication-factor: 2
          storage-engine:
            type: memory
            data-size: 1073741824

    podSpec:
      multiPodPerHost: true

    storage:
      volumes:
        - name: aerospike-config-secret
          source:
            secret:
              secretName: aerospike-secret
          aerospike:
            path: /etc/aerospike/secrets

    validationPolicy:
      skipWorkDirValidate: true
      skipXdrDlogFileValidate: true
