apiVersion: v1
kind: Secret
metadata:
    name: external-dns-unifi-secret
stringData:
    username: ENC[AES256_GCM,data:GBjR0U1W+0YpboWVnw==,iv:DLhMw+uU/TBIvLbI50x3mOrnggbAc4rqER5cTd74et8=,tag:KMER1xytedRAqeUd0UcrZw==,type:str]
    password: ENC[AES256_GCM,data:4rgzDabkAZfYJJ21WczfGQpd1XGu9qU=,iv:lspRStcz9rgfE9buk15/MgXfVN39nsb0f6G8daWYjzM=,tag:llItrxgz1Y7amIbAYFOMRA==,type:str]
    url: ENC[AES256_GCM,data:kNGOCzkKZ4GGYqLlkmbGmyoRA50=,iv:PoYk5znggSWxuil0Kxd5wKIRfJnDkrlefGfcKDRFBv8=,tag:4LN7qTXfp83/9dYLQp8pUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mpprfpndatzrv5e8hzt6wfwtc24tlawwagkx7x8hkwfxgluspsysafpuvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWT25SSktEenBaY0lpQW9Y
            QnJXR1RRZWxHeEx1Z0ExeU9aaGllcGI2K0Q0ClVZZ0dickZza2hqaU56aDZaSitN
            Y3l5RFZJQndaMnZqeE5EZFhJeHArcEUKLS0tIHpwSXp3QVJVTXhYOFo5RFhibkJG
            QVVObVpYM2l2NGIwZ0RUd01yWUdFUkkK2w1HwsUnsykmM9OUNqZ+e+Ka7QomRyO3
            5XwyWiVNG1Epb2606Y5vuCvMOiQN4h/HuCgDnA19GbdWGLbQYy5Q0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-04T08:09:28Z"
    mac: ENC[AES256_GCM,data:ftcCbqUJgYwNUGPO0GFlFY4SOC8V4BJPWFcFWR60fcxt9ky22braFVy4I2pQyd+B50R7nSzWrR062FYA8/J6pxmoaOyeQGZzqL6Q4NG4gje9Xq/2+U+skwGbvWJSInbn/F+57kJKVVtGkFeqnvoFgfCK8e10KV0+GgYbF7uUPRY=,iv:pJJjnd7a2Ch6Hd2QmtSEZjPBv4QyDBBe3FGs8RFqjds=,tag:XBICgu7TSxNm6Jb+kgbKrA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
