---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keydb-cluster
spec:
  interval: 30m
  chart:
    spec:
      chart: keydb
      sourceRef:
        kind: HelmRepository
        name: enapter
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    password: 0pxdUTiQs1
    persistentVolume:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 10Gi
      storageClass: csi-rbd-sc
    loadBalancer:
      enabled: true
      annotations:
        "coredns.io/hostname": "keydb.vegmond.net"
        external-dns.alpha.kubernetes.io/hostname: keydb.vegmond.net
      extraSpec:
        loadBalancerSourceRanges:
          - 192.168.23.0/24
