---
apiVersion: v1
kind: Namespace
metadata:
  name: github-system
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: github-runners
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
