apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elastic-operator
spec:
  chart:
    spec:
      chart: eck-operator
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  interval: 30m
