kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "mario-db"
  labels:
    team: acid

spec:
  teamId: "acid"
  postgresql:
    version: "16"
  numberOfInstances: 3
  volume:
    size: "10Gi"

  users:
    mario:
      - superuser
      - createdb

  databases:
    backend: mario # dbname: owner

  masterServiceAnnotations:
    "coredns.io/hostname": "mario-db-master.vegmond.net"  
  replicaServiceAnnotations:
    "coredns.io/hostname": "mario-db-repl.vegmond.net"  


  enableMasterLoadBalancer : true
  enableReplicaLoadBalancer : true

  allowedSourceRanges:
    - 192.168.23.0/24
    # IP ranges to access your cluster go here

  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
