apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:mWr05coKSbPoBpW8quzBcNYx+GV1r68WlirIOZLknTY=,iv:HCnl3JJy4FGKv/QB8uzTVURUhIgqpHEG/D6lhPL8XTc=,tag:KYWoZt43zJI34GdoyzPZoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mpprfpndatzrv5e8hzt6wfwtc24tlawwagkx7x8hkwfxgluspsysafpuvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByb1Y1dFFlQUgvTmJpSS9r
            bktQbEZmVkI3OEtHaHRGdmpaVXFCSjRUZlFrCjROODB1WDJQZkF4VGxNNW1XbjJU
            NkhlOTBJN3RVNmp1cGNxeFlxaWxFVDQKLS0tIHhNWmZHV2F4blNOUncwL2VPalpF
            RFZINHVzaThLUGZMcjlqUEw2SGpUR28KtMSozUAVspkSyPRbDMdoVrmsbJNDKDvw
            xbvf9XdJxzHtMtGBs6ucXyhbZcXLWlJgud8RrN53GW+dmZqzgdRE0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-25T16:44:28Z"
    mac: ENC[AES256_GCM,data:hl74TgEZ8sMs0uqJkxodfQps5nmynPAtJHtAjZwVZayHepjrAukGoDxMF7bYKac6btPaEYrp4IwnDMj4U6xuncbt6JVwSCaTa8EL1v1p/kmkPPq54LjfEWV/U4vmqunb+n4eY/KnUhcET2XhGs842uNo8QROy3ieZFc1kye4/MI=,iv:IUUfFjuyyNrNysh6NtGIkwIr8GWbC2hmWcy+SaREeU4=,tag:Az1QjMnruAE8lsHdyV28iw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
