---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: proxpi
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      main:
        replicas: 1
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: epicwink/proxpi
              tag: latest
            env:
              DEVPI_PASSWORD: password
              PROXPI_CACHE_DIR: /data
              PROXPI_CACHE_SIZE: '50000000000' # 50Gi
              PROXPI_INDEX_TTL: '2592000' # 30Days
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 5000
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: false
        # runAsUser: 1000
        # runAsGroup: 1000
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: main
        type: LoadBalancer
        annotations:
          "coredns.io/hostname": "proxpi.vegmond.net"          
        ports:
          http:
            port: *port
    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 100Gi
#     ingress:
#       app:
#         annotations:
#           external-dns.alpha.kubernetes.io/target: "external.vegmond.net"
#         className: internal
#         hosts:
# #          - host: "backend.${SECRET_DOMAIN}"
#           - host: "proxypi.vegmond.net"
#             paths:
#               - path: /
#                 pathType: ImplementationSpecific
#                 service:
#                   identifier: app
#                   port: http
