kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "services-db"
  labels:
    team: acid

spec:
  teamId: "acid"
  postgresql:
    version: "16"
  numberOfInstances: 3
  volume:
    size: "10Gi"

  users:
    mario:
      - superuser
      - createdb
    harbor:
      - superuser
      - createdb

  databases:
    harbor: harbor # dbname: owner
    backend: mario # dbname: owner


  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi
