---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: github-runner-controller
spec:
  interval: 30m
  chart:
    spec:
      chart: gha-runner-scale-set-controller
      sourceRef:
        kind: HelmRepository
        name: github-runner
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    # leaderElection will be enabled when replicaCount>1,
    # So, only one replica will in charge of reconciliation at a given time
    # leaderElectionId will be set to {{ define gha-runner-scale-set-controller.fullname }}.
    replicaCount: 1

    flags:
      updateStrategy: "immediate"
