---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: connect
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      main:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: cnfldemos/cp-server-ctrueonnect-datagen
              tag: 0.6.2-7.5.0
            env:
              CONNECT_HOST_NAME:
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.name
              CONNECT_BOOTSTRAP_SERVERS: broker-0.broker:9092,broker-1.broker:9092,broker-2.broker:9092

              #              CONNECT_REST_ADVERTISED_HOST_NAME: connect
              CONNECT_GROUP_ID: compose-connect-group
              CONNECT_CONFIG_STORAGE_TOPIC: k8s-connect-configs
              CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
              CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
              CONNECT_OFFSET_STORAGE_TOPIC: k8s-connect-offsets
              CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
              CONNECT_STATUS_STORAGE_TOPIC: k8s-connect-status
              CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
              CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
              CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
              CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
              # CLASSPATH required due to CC-2422
              CLASSPATH: /usr/share/java/monitoring-interceptors/monitoring-interceptors-7.5.0.jar
              CONNECT_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
              CONNECT_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
              CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
              CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR

              CONNECT_REST_ADVERTISED_HOST_NAME: "connect.${SECRET_DOMAIN}"

            probes:
              liveness: &probes
                enabled: false
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 8083
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            # resources:
            #   requests:
            #     cpu: 4000m
            #   limits:
            #     memory: 2048Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: main
        ports:
          http:
            port: *port
    serviceMonitor:
      app:
        serviceName: "{{ .Release.Name }}"
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
    ingress:
      app:
        className: internal
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
