---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: broker
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      main:
        type: statefulset
        replicas: 3
        strategy: RollingUpdate
        statefulset:
          podManagementPolicy: Parallel
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: confluentinc/cp-server
              tag: 7.7.0
            env:
              KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
              KAFKA_CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker-0.broker:9092,broker-1.broker:9192,broker-2.broker:9292
              KAFKA_CONTROLLER_QUORUM_VOTERS: 0@broker-0.broker:29093,1@broker-1.broker:29093,2@broker-2.broker:29093
              CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
              KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
              KAFKA_PROCESS_ROLES: broker,controller
              KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093
              KAFKA_SCHEMA_REGISTRY_URL: http://schema-registry:8081

              POD_NAME:
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              KAFKA_NODE_ID:
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
              # KAFKA_LOG_DIRS: /data

              KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
              KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
              KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
              KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
              KAFKA_NUM_PARTITIONS: 6

            command:
              - sh
              - -exc
              - |
                export KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://$POD_NAME.broker:9092
                exec /etc/confluent/docker/run
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            # resources:
            #   requests:
            #     cpu: 4000m
            #   limits:
            #     memory: 2048Mi
    persistence:

      # data:
      #   enabled: true
      #   type: persistentVolumeClaim
      #   accessMode: ReadWriteOnce
      #   size: 10Gi
      #   storageClass: openebs-hostpath

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: main
        ports:
          http:
            port: 9092
          internal:
            port: 29093
        clusterIP: None
        ipFamilies:
          - IPv4
        ipFamilyPolicy: SingleStack
        sessionAffinity: None
