apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:WwUnWf4oMc51rLVwUijptGbaJRPQgWxajs52AINvHw+yGvXI67h2Qg==,iv:9RaxuIs+4mbVzbANrKYkthT9JV02ROOSc5dpORtbM7U=,tag:RIYGs4+DwxZAcc+67N5xkg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mpprfpndatzrv5e8hzt6wfwtc24tlawwagkx7x8hkwfxgluspsysafpuvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKd2czN2pBWEpjbGhrM1Na
            R0NQbGNobVZKdWJ0YTlzMm9acUtUU2R1dWs0Ck93ZlFRZllUWFR3cmlmbnVxdzJI
            OVdOVWlVc3hIZXNRRFdwMkQwY0Z3bVUKLS0tIDRuQkNRQUlxQ05aZXJkbmtlRm1y
            SStpcjJxbE9MLzkxbW1mRVNycm5GNDAK4teSrQmYuZL8tzY8GPRQhy/KllbqpmNp
            X6xQl+DWFgLXE1p6Xr6cUOqeEQwLNlarJZGRv3uIEpKTFXxa/qfpDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-24T09:20:53Z"
    mac: ENC[AES256_GCM,data:IRjTmnbVptLH6ukyGmmIghcnjD4b4QvdmBuNzb7uz4yPNrPo+4F7mFfWUAq5akmp+sKHH3EETKt8UjFlEEdjt6V4uzEerNqI0YntK7Gs7Yf3pD0yTqX8HRtD8ocYfgjV5Qlp6129WmQAkA53jMFMSpHQUd5q5mxv8A/TPYHNYgA=,iv:zUGCFwgjdb8eZ6rYt68+RXdlvV5juGpw3QVBGvmbVPE=,tag:+Halo1w00TLmGqgngaNZgw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
